<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Images\Branding\LogoMin.png" />
    <Resource Include="Images\Branding\Logo.png" />
    <Resource Include="Images\Placeholder\TaskbarBackgroundColor.png" />
  </ItemGroup>

</Project>
