<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="coffee logo.png" />
    <None Remove="taskbar background colour.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="coffee logo.png" />
    <Resource Include="taskbar background colour.png" />
  </ItemGroup>

</Project>
